### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by rijinrij** [PushpenderIndia/subdover#1] opened 2020-09-02 13:43 UTC
File "subdover.py", line 182, in <module>
    os.rename(f"{arguments.subdomain_list}-httpx.txt", f"{arguments.subdomain_list}")
FileNotFoundError: [Errno 2] No such file or directory: 'example_target.txt-httpx.txt' -> 'example_target.txt'

**Comment by PushpenderIndia** [comment] 2020-09-03 06:22
Make sure to give full path of subdomainList after --list parameter

**Comment by PushpenderIndia** [comment] 2020-09-03 07:14
On which system, you are using subdover ?

**Comment by rijinrij** [comment] 2020-09-05 06:22
Kali on WSL

**Comment by PushpenderIndia** [comment] 2020-09-07 05:24
Please Clone Latest Edition of Subdover and try again!

Now it should be fixed

**Comment by rijinrij** [comment] 2020-09-07 15:46
thanks fixed

**Comment by rijinrij** [comment] 2020-09-07 15:46
root@MrCyguru:/opt/subdover# python3 subdover.py --help
Traceback (most recent call last):
  File "subdover.py", line 1, in <module>
    from src.fingerprints import *
ModuleNotFoundError: No module named 'src.fingerprints'

**Comment by PushpenderIndia** [comment] 2020-09-17 13:00
Added __init__.py file in src directory, now check again that the issue is solved or not

**Closed** 2020-09-17 14:18 UTC
